image:
  repository: ghcr.io/ferriskey/ferriskey-docs
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: docs.ferriskey.bonnal.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ferriskey-docs-tls
      hosts:
        - docs.ferriskey.bonnal.cloud