front:
  image:
    repository: ghcr.io/ferriskey/ferriskey-front
    pullPolicy: Always
    tag: "latest"
  labels:
    app: ferriskey-front
  service:
    type: ClusterIP
    port: 80
  apiUrl: "https://api.ferriskey.bonnal.cloud"
api:
  replicaCount: 1
  portalUrl: "https://console.ferriskey.bonnal.cloud"
  image:
    repository: ghcr.io/ferriskey/ferriskey-api
    pullPolicy: Always
    tag: "latest"
  service:
    type: ClusterIP
    port: 3333
  database:
    existingSecret: infrastructure-ferriskey-stack-db-app
    existingSecretUrlKey: uri
  healthCheck:
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 3
      successThreshold: 1

ingress:
  enabled: true
  apiHost: "api.ferriskey.bonnal.cloud"
  frontHost: "console.ferriskey.bonnal.cloud"

  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod

  tls:
    enabled: true


env: "development"

allowedOrigins: "https://console.ferriskey.bonnal.cloud,http://localhost:3000,http://localhost:5555,http://localhost:5173,http://localhost:8080,http://localhost:8000,https://ferriskey.fr,https://ferriskey.dev,https://ferriskey.io,https://ferriskey.app"

auth:
  password: "admin"
  username: "admin"
  email: "admin@ferriskey.fr"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""



# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 3333