version: '3.8'

services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ferriskey
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  keycloak-db-init:
    image: postgres:17
    depends_on:
      - postgres
    environment:
      - PGPASSWORD=postgres
    command: >
      bash -c "
        echo 'Creating keycloak database...' &&
        psql -h postgres -U postgres -c 'CREATE DATABASE keycloak;' &&
        echo 'Keycloak database created successfully!'
      "
    restart: on-failure


  keycloak:
    image: bitnami/keycloak:26.0.0
    environment:
      KEYCLOAK_ADMIN: super
      KEYCLOAK_ADMIN_PASSWORD: super
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: postgres
      KEYCLOAK_DATABASE_NAME: keycloak
    depends_on:
      - postgres
    ports:
      - 8080:8080

volumes:
  postgres_data:
