apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: ferriskey-operator
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: operator
