/*
 Generated by typeshare 1.13.2
*/

export interface AuthResponse {
	url: string;
}

export interface AuthenticateQueryParams {
	client_id: string;
}

export interface AuthenticateRequest {
	username?: string;
	password?: string;
}

export interface AuthenticateResponse {
	url: string;
}

