apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ferriskey.fullname" . }}-api
  labels:
    {{- include "ferriskey.labels" . | nindent 4 }}
    component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      {{- include "ferriskey.selectorLabels" . | nindent 6 }}
      component: api
  template:
    metadata:
      labels:
        {{- include "ferriskey.labels" . | nindent 8 }}
        component: api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      #serviceAccountName: {{ include "ferriskey.serviceAccountName" . }}
      initContainers:
        - name: migrations
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              sqlx migrate run &&
              echo 'Database migrations completed!'
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: ENV
              value: {{ .Values.env | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.api.database.existingSecretUrlKey }}
                  name: {{ .Values.api.database.existingSecret }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.auth.password }}
            - name: ADMIN_USERNAME
              value: {{ .Values.auth.username | quote }}
            - name: ADMIN_EMAIL
              value: {{ .Values.auth.email | quote }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.allowedOrigins | quote }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.api.service.port }}
              protocol: TCP
          {{- if .Values.api.healthCheck.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /health/live
              port: {{ .Values.api.service.port }}
            initialDelaySeconds: {{ .Values.api.healthCheck.livenessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.api.healthCheck.livenessProbe.periodSeconds | default 10 }}
            timeoutSeconds: {{ .Values.api.healthCheck.livenessProbe.timeoutSeconds | default 5 }}
            failureThreshold: {{ .Values.api.healthCheck.livenessProbe.failureThreshold | default 3 }}
          {{- end }}
          {{- if .Values.api.healthCheck.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /health/ready
              port: http
            initialDelaySeconds: {{ .Values.api.healthCheck.readinessProbe.initialDelaySeconds | default 5 }}
            periodSeconds: {{ .Values.api.healthCheck.readinessProbe.periodSeconds | default 5 }}
            timeoutSeconds: {{ .Values.api.healthCheck.readinessProbe.timeoutSeconds | default 3 }}
            failureThreshold: {{ .Values.api.healthCheck.readinessProbe.failureThreshold | default 3 }}
            successThreshold: {{ .Values.api.healthCheck.readinessProbe.successThreshold | default 1 }}
          {{- end }}
          env:
            - name: PORT
              value: {{ .Values.api.service.port | quote }}
            - name: ENV
              value: {{ .Values.env | quote }}
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.api.database.existingSecretUrlKey }}
                  name: {{ .Values.api.database.existingSecret }}
            - name: ADMIN_PASSWORD
              value: {{ .Values.auth.password }}
            - name: ADMIN_USERNAME
              value: {{ .Values.auth.username | quote }}
            - name: ADMIN_EMAIL
              value: {{ .Values.auth.email | quote }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.allowedOrigins | quote }}
            - name: PORTAL_URL
              value: {{ .Values.api.portalUrl | quote }}
