apiVersion: v2
name: infrastructure
description: A Helm chart for Kubernetes

type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: keda
    version: 2.17.0  # Vérifie la version actuelle sur https://artifacthub.io/packages/helm/kedacore/keda
    repository: https://kedacore.github.io/charts
  - name: cloudnative-pg
    version: 0.19.1  # Check for the latest version on https://artifacthub.io/packages/helm/cloudnative-pg/cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts