argo-cd:
  namespaceOverride: "argocd"
  redis-ha:
    enabled: true

  controller:
    replicas: 1
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: monitoring

  server:
    replicas: 2

  repoServer:
    replicas: 2

  applicationSet:
    replicas: 2