name: 🐛 Bug Report
description: Report a reproducible bug in FerrisKey
labels: [type:bug]
body:
  - type: textarea
    attributes:
      label: Description
      description: Clearly describe the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: List the exact steps to reproduce the issue.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What should have happened instead?
  - type: textarea
    attributes:
      label: Logs or Screenshots
      description: Paste relevant logs, errors, or screenshots.
  - type: dropdown
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
