name: 📚 Documentation Improvement
description: Suggest improvements to the documentation
labels: [type:doc]
body:
  - type: textarea
    attributes:
      label: What needs improvement?
      description: Be specific about the area of the documentation that could be improved.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Current State
      description: Explain what is currently unclear, missing, or outdated.
  - type: textarea
    attributes:
      label: Proposed Improvement
      description: Suggest what should be added or changed.
