{{- if .Values.api.admin.passwordSecret.create }}
{{- $name := include "ferriskey.api.adminSecretName" . -}}
{{- $secret := lookup "v1" "Secret" .Release.Namespace $name -}}
{{- $password := "" -}}
{{- if $secret -}}
{{- $password = $secret.data.password -}}
{{- else -}}
{{- $password = randAlpha 16 | b64enc -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  {{- with .Values.api.admin.passwordSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ferriskey.api.labels" . | nindent 4 }}
    {{- with .Values.api.admin.passwordSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  password: {{ $password }}
type: Opaque
{{- end }}
