{{- $annotations := merge dict .Values.common.service.annotations .Values.api.service.annotations -}}
{{- $labels := merge dict .Values.common.service.labels .Values.api.service.labels -}}
{{- $loadBalancerClass := .Values.api.service.loadBalancerClass | default .Values.common.service.loadBalancerClass -}}
{{- $loadBalancerSourceRanges := concat .Values.common.service.loadBalancerSourceRanges .Values.api.service.loadBalancerSourceRanges -}}
{{- $externalTrafficPolicy := .Values.api.service.externalTrafficPolicy | default .Values.common.service.externalTrafficPolicy -}}
{{- $internalTrafficPolicy := .Values.api.service.internalTrafficPolicy | default .Values.common.service.internalTrafficPolicy -}}
{{- $publishNotReadyAddresses := include "ferriskey.util.bool" (dict "value" .Values.api.service.publishNotReadyAddresses "default" .Values.common.service.publishNotReadyAddresses) -}}
{{- $sessionAffinity := .Values.api.service.sessionAffinity | default .Values.common.service.sessionAffinity -}}
{{- $sessionAffinityConfig := merge dict .Values.common.service.sessionAffinityConfig .Values.api.service.sessionAffinityConfig -}}
{{- $trafficDistribution := .Values.api.service.trafficDistribution | default .Values.common.service.trafficDistribution -}}
{{- $type := .Values.api.service.type | default .Values.common.service.type -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferriskey.api.name" . }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "ferriskey.api.labels" . | nindent 4 }}
    {{- with $labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.api.service.clusterIP }}
  clusterIP: {{ .Values.api.service.clusterIP }}
  {{- end }}
  {{- with .Values.api.service.clusterIPs }}
  clusterIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.api.service.externalIPs }}
  externalIPs:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.api.service.externalName }}
  externalName: {{ .Values.api.service.externalName }}
  {{- end }}
  {{- if $externalTrafficPolicy }}
  externalTrafficPolicy: {{ $externalTrafficPolicy }}
  {{- end }}
  {{- if ne .Values.api.service.healthCheckNodePort nil }}
  healthCheckNodePort: {{ .Values.api.service.healthCheckNodePort }}
  {{- end }}
  {{- if $internalTrafficPolicy }}
  internalTrafficPolicy: {{ $internalTrafficPolicy }}
  {{- end }}
  {{- with .Values.api.service.ipFamilies }}
  ipFamilies:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.api.service.ipFamilyPolicy }}
  ipFamilyPolicy: {{ .Values.api.service.ipFamilyPolicy }}
  {{- end }}
  {{- if $loadBalancerClass }}
  loadBalancerClass: {{ $loadBalancerClass }}
  {{- end }}
  {{- if .Values.api.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.api.service.loadBalancerIP }}
  {{- end }}
  {{- with $loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.api.server.port }}
      protocol: TCP
      targetPort: http
  {{- if ne $publishNotReadyAddresses "" }}
  publishNotReadyAddresses: {{ $publishNotReadyAddresses }}
  {{- end }}
  selector:
    {{- include "ferriskey.api.podLabels" . | nindent 4 }}
  {{- if $sessionAffinity }}
  sessionAffinity: {{ $sessionAffinity }}
  {{- end }}
  {{- with $sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if $trafficDistribution }}
  trafficDistribution: {{ $trafficDistribution }}
  {{- end }}
  type: {{ $type }}
