apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Release.Name }}-pg-auth
  namespace: {{ .Release.Namespace }}
spec:
  secretTargetRef:
    - parameter: username
      name: infrastructure-ferriskey-stack-db-app
      key: username
    - parameter: password
      name: infrastructure-ferriskey-stack-db-app
      key: password
