//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "consent_session_scopes"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub consent_session_id: Uuid,
    pub scope: String,
    pub granted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    ConsentSessionId,
    Scope,
    Granted,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    ConsentSessionId,
    Scope,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = (Uuid, String);
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ConsentSessions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::ConsentSessionId => ColumnType::Uuid.def(),
            Self::Scope => ColumnType::Text.def(),
            Self::Granted => ColumnType::Boolean.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ConsentSessions => Entity::belongs_to(super::consent_sessions::Entity)
                .from(Column::ConsentSessionId)
                .to(super::consent_sessions::Column::Id)
                .into(),
        }
    }
}

impl Related<super::consent_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConsentSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
