//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "device_auth_sessions"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub device_code: Uuid,
    pub user_code: String,
    pub client_id: Uuid,
    pub realm_id: Uuid,
    pub user_id: Option<Uuid>,
    pub scope: Option<String>,
    pub status: String,
    pub interval_seconds: i32,
    pub expires_at: DateTimeWithTimeZone,
    pub last_polled_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    DeviceCode,
    UserCode,
    ClientId,
    RealmId,
    UserId,
    Scope,
    Status,
    IntervalSeconds,
    ExpiresAt,
    LastPolledAt,
    CreatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    DeviceCode,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Clients,
    Realms,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::DeviceCode => ColumnType::Uuid.def(),
            Self::UserCode => ColumnType::String(StringLen::N(9u32)).def().unique(),
            Self::ClientId => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::UserId => ColumnType::Uuid.def().null(),
            Self::Scope => ColumnType::Text.def().null(),
            Self::Status => ColumnType::String(StringLen::N(32u32)).def(),
            Self::IntervalSeconds => ColumnType::Integer.def(),
            Self::ExpiresAt => ColumnType::TimestampWithTimeZone.def(),
            Self::LastPolledAt => ColumnType::TimestampWithTimeZone.def().null(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Clients => Entity::belongs_to(super::clients::Entity)
                .from(Column::ClientId)
                .to(super::clients::Column::Id)
                .into(),
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
