//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "realms")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_sessions::Entity")]
    AuthSessions,
    #[sea_orm(has_many = "super::clients::Entity")]
    Clients,
    #[sea_orm(has_many = "super::jwt_keys::Entity")]
    JwtKeys,
    #[sea_orm(has_many = "super::magic_links::Entity")]
    MagicLinks,
    #[sea_orm(has_many = "super::realm_settings::Entity")]
    RealmSettings,
    #[sea_orm(has_many = "super::roles::Entity")]
    Roles,
    #[sea_orm(has_many = "super::security_events::Entity")]
    SecurityEvents,
    UserFederationProviders,
    UserSessions,
    #[sea_orm(has_many = "super::users::Entity")]
    Users,
    #[sea_orm(has_many = "super::webhooks::Entity")]
    Webhooks,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::Name => ColumnType::String(StringLen::N(255u32)).def().unique(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AuthSessions => Entity::has_many(super::auth_sessions::Entity).into(),
            Self::Clients => Entity::has_many(super::clients::Entity).into(),
            Self::JwtKeys => Entity::has_many(super::jwt_keys::Entity).into(),
            Self::RealmSettings => Entity::has_many(super::realm_settings::Entity).into(),
            Self::Roles => Entity::has_many(super::roles::Entity).into(),
            Self::SecurityEvents => Entity::has_many(super::security_events::Entity).into(),
            Self::UserFederationProviders => {
                Entity::has_many(super::user_federation_providers::Entity).into()
            }
            Self::UserSessions => Entity::has_many(super::user_sessions::Entity).into(),
            Self::Users => Entity::has_many(super::users::Entity).into(),
            Self::Webhooks => Entity::has_many(super::webhooks::Entity).into(),
        }
    }
}

impl Related<super::auth_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthSessions.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::jwt_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JwtKeys.def()
    }
}

impl Related<super::magic_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MagicLinks.def()
    }
}

impl Related<super::realm_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RealmSettings.def()
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Roles.def()
    }
}

impl Related<super::security_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SecurityEvents.def()
    }
}

impl Related<super::user_federation_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationProviders.def()
    }
}

impl Related<super::user_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSessions.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl Related<super::webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Webhooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
