//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub realm_id: Uuid,
    #[sea_orm(unique)]
    pub client_id: Option<Uuid>,
    pub username: String,
    pub firstname: String,
    pub lastname: String,
    pub email: String,
    pub email_verified: bool,
    pub enabled: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auth_sessions::Entity")]
    AuthSessions,
    #[sea_orm(
        belongs_to = "super::clients::Entity",
        from = "Column::ClientId",
        to = "super::clients::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Clients,
    #[sea_orm(has_many = "super::credentials::Entity")]
    Credentials,
    #[sea_orm(has_many = "super::magic_links::Entity")]
    MagicLinks,
    #[sea_orm(
        belongs_to = "super::realms::Entity",
        from = "Column::RealmId",
        to = "super::realms::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Realms,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    UserFederationMappings,
    UserRequiredActions,
    #[sea_orm(has_many = "super::user_role::Entity")]
    UserRole,
    #[sea_orm(has_many = "super::user_sessions::Entity")]
    UserSessions,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::ClientId => ColumnType::Uuid.def().null().unique(),
            Self::Username => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Firstname => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Lastname => ColumnType::String(StringLen::N(255u32)).def(),
            Self::Email => ColumnType::String(StringLen::N(255u32)).def(),
            Self::EmailVerified => ColumnType::Boolean.def(),
            Self::Enabled => ColumnType::Boolean.def(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::AuthSessions => Entity::has_many(super::auth_sessions::Entity).into(),
            Self::Clients => Entity::belongs_to(super::clients::Entity)
                .from(Column::ClientId)
                .to(super::clients::Column::Id)
                .into(),
            Self::Credentials => Entity::has_many(super::credentials::Entity).into(),
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::RefreshTokens => Entity::has_many(super::refresh_tokens::Entity).into(),
            Self::UserFederationMappings => {
                Entity::has_many(super::user_federation_mappings::Entity).into()
            }
            Self::UserRequiredActions => {
                Entity::has_many(super::user_required_actions::Entity).into()
            }
            Self::UserRole => Entity::has_many(super::user_role::Entity).into(),
            Self::UserSessions => Entity::has_many(super::user_sessions::Entity).into(),
        }
    }
}

impl Related<super::auth_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthSessions.def()
    }
}

impl Related<super::clients::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Clients.def()
    }
}

impl Related<super::credentials::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Credentials.def()
    }
}

impl Related<super::magic_links::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MagicLinks.def()
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::user_federation_mappings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFederationMappings.def()
    }
}

impl Related<super::user_required_actions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRequiredActions.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl Related<super::user_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
