//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "webhook_deliveries"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub realm_id: Uuid,
    pub webhook_id: Uuid,
    pub event: String,
    pub resource_id: Uuid,
    pub payload: Json,
    pub status: String,
    pub attempt_count: i32,
    pub next_attempt_at: Option<DateTime>,
    pub leased_until: Option<DateTime>,
    pub last_attempt_at: Option<DateTime>,
    pub last_status_code: Option<i32>,
    pub last_error_code: Option<String>,
    pub last_error_detail: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    RealmId,
    WebhookId,
    Event,
    ResourceId,
    Payload,
    Status,
    AttemptCount,
    NextAttemptAt,
    LeasedUntil,
    LastAttemptAt,
    LastStatusCode,
    LastErrorCode,
    LastErrorDetail,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Realms,
    Webhooks,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::RealmId => ColumnType::Uuid.def(),
            Self::WebhookId => ColumnType::Uuid.def(),
            Self::Event => ColumnType::String(StringLen::N(64u32)).def(),
            Self::ResourceId => ColumnType::Uuid.def(),
            Self::Payload => ColumnType::JsonBinary.def(),
            Self::Status => ColumnType::String(StringLen::N(16u32)).def(),
            Self::AttemptCount => ColumnType::Integer.def(),
            Self::NextAttemptAt => ColumnType::DateTime.def().null(),
            Self::LeasedUntil => ColumnType::DateTime.def().null(),
            Self::LastAttemptAt => ColumnType::DateTime.def().null(),
            Self::LastStatusCode => ColumnType::Integer.def().null(),
            Self::LastErrorCode => ColumnType::String(StringLen::N(32u32)).def().null(),
            Self::LastErrorDetail => ColumnType::String(StringLen::N(512u32)).def().null(),
            Self::CreatedAt => ColumnType::DateTime.def(),
            Self::UpdatedAt => ColumnType::DateTime.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Realms => Entity::belongs_to(super::realms::Entity)
                .from(Column::RealmId)
                .to(super::realms::Column::Id)
                .into(),
            Self::Webhooks => Entity::belongs_to(super::webhooks::Entity)
                .from(Column::WebhookId)
                .to(super::webhooks::Column::Id)
                .into(),
        }
    }
}

impl Related<super::realms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Realms.def()
    }
}

impl Related<super::webhooks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Webhooks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
