# infrastructure/charts/ferriskey/templates/front/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ferriskey.fullname" . }}-front
  labels: {{- include "ferriskey.labels" . | nindent 4 }}
spec:
  type: {{ .Values.front.service.type }}
  ports:
    - port: {{ .Values.front.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ferriskey.selectorLabels" . | nindent 4 }}
    component: front
