//! The authorization decision table.
//!
//! One row per `ensure_policy` call site: what the operation is
//! (`action`), and what the engine actually checks today (`policy_fn`,
//! `permissions`). Divergence between the two is a finding, not a
//! formatting detail — this table is the specification the current
//! engine never had, and the oracle any replacement is judged against.
//!
//! Generated from the source tree, then reviewed by hand. Regenerate
//! after adding a call site; `matrix_covers_every_call_site` fails
//! until the table matches.

use ferriskey_domain::role::permission::Permissions;

use crate::actions;
use crate::entities::{ActionId, EntityType};

/// One authorization-guarded operation.
pub struct AuthzRow {
    /// `module::function` of the service method performing the operation.
    pub service_fn: &'static str,
    /// The `can_*` policy method it currently calls.
    pub policy_fn: &'static str,
    /// What the operation means, independent of how it is checked.
    pub action: ActionId,
    /// The entity type the policy is scoped to.
    pub resource: EntityType,
    /// Permissions the policy accepts; holding any one of them grants.
    pub permissions: &'static [Permissions],
    /// The policy short-circuits to allow when subject == target.
    pub self_bypass: bool,
    /// Source location, so a failing test points at the real code.
    pub file: &'static str,
    pub line: u32,
}

pub const AUTHZ_MATRIX: &[AuthzRow] = &[
    AuthzRow {
        service_fn: "create_federation_provider",
        policy_fn: "can_create_federation_provider",
        action: actions::FEDERATION_PROVIDER_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/federation/services.rs",
        line: 92,
    },
    AuthzRow {
        service_fn: "get_federation_provider",
        policy_fn: "can_view_federation_provider",
        action: actions::FEDERATION_PROVIDER_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/federation/services.rs",
        line: 128,
    },
    AuthzRow {
        service_fn: "update_federation_provider",
        policy_fn: "can_update_federation_provider",
        action: actions::FEDERATION_PROVIDER_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/federation/services.rs",
        line: 162,
    },
    AuthzRow {
        service_fn: "delete_federation_provider",
        policy_fn: "can_delete_federation_provider",
        action: actions::FEDERATION_PROVIDER_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/federation/services.rs",
        line: 198,
    },
    AuthzRow {
        service_fn: "create_identity_provider",
        policy_fn: "can_create_identity_provider",
        action: actions::IDENTITY_PROVIDER_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/identity_provider_services.rs",
        line: 90,
    },
    AuthzRow {
        service_fn: "get_identity_provider",
        policy_fn: "can_view_identity_provider",
        action: actions::IDENTITY_PROVIDER_READ,
        resource: EntityType::new("IdentityProvider"),
        permissions: &[Permissions::ManageRealm, Permissions::ViewRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/identity_provider_services.rs",
        line: 157,
    },
    AuthzRow {
        service_fn: "update_identity_provider",
        policy_fn: "can_update_identity_provider",
        action: actions::IDENTITY_PROVIDER_UPDATE,
        resource: EntityType::new("IdentityProvider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/identity_provider_services.rs",
        line: 238,
    },
    AuthzRow {
        service_fn: "delete_identity_provider",
        policy_fn: "can_delete_identity_provider",
        action: actions::IDENTITY_PROVIDER_DELETE,
        resource: EntityType::new("IdentityProvider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/identity_provider_services.rs",
        line: 292,
    },
    AuthzRow {
        service_fn: "create_provider",
        policy_fn: "can_create_provider",
        action: actions::PROVIDER_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 119,
    },
    AuthzRow {
        service_fn: "get_provider",
        policy_fn: "can_view_provider",
        action: actions::PROVIDER_READ,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm, Permissions::ViewRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 176,
    },
    AuthzRow {
        service_fn: "update_provider",
        policy_fn: "can_update_provider",
        action: actions::PROVIDER_UPDATE,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 252,
    },
    AuthzRow {
        service_fn: "delete_provider",
        policy_fn: "can_delete_provider",
        action: actions::PROVIDER_DELETE,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 344,
    },
    AuthzRow {
        service_fn: "toggle_provider",
        policy_fn: "can_update_provider",
        action: actions::PROVIDER_TOGGLE,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 377,
    },
    AuthzRow {
        service_fn: "create_provider_mapping",
        policy_fn: "can_update_provider",
        action: actions::PROVIDER_MAPPING_CREATE,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 409,
    },
    AuthzRow {
        service_fn: "list_provider_mappings",
        policy_fn: "can_view_provider",
        action: actions::PROVIDER_MAPPING_LIST,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm, Permissions::ViewRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 455,
    },
    AuthzRow {
        service_fn: "delete_provider_mapping",
        policy_fn: "can_update_provider",
        action: actions::PROVIDER_MAPPING_DELETE,
        resource: EntityType::new("Provider"),
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/abyss/services.rs",
        line: 494,
    },
    AuthzRow {
        service_fn: "create_client",
        policy_fn: "can_create_client",
        action: actions::CLIENT_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 145,
    },
    AuthzRow {
        service_fn: "create_redirect_uri",
        policy_fn: "can_create_client",
        action: actions::CLIENT_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 239,
    },
    AuthzRow {
        service_fn: "create_post_logout_redirect_uri",
        policy_fn: "can_create_client",
        action: actions::CLIENT_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 277,
    },
    AuthzRow {
        service_fn: "create_role",
        policy_fn: "can_create_role",
        action: actions::ROLE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 315,
    },
    AuthzRow {
        service_fn: "delete_client",
        policy_fn: "can_delete_client",
        action: actions::CLIENT_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 369,
    },
    AuthzRow {
        service_fn: "delete_redirect_uri",
        policy_fn: "can_update_client",
        action: actions::CLIENT_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 418,
    },
    AuthzRow {
        service_fn: "delete_post_logout_redirect_uri",
        policy_fn: "can_update_client",
        action: actions::CLIENT_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 455,
    },
    AuthzRow {
        service_fn: "get_client_by_id",
        policy_fn: "can_view_client",
        action: actions::CLIENT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 491,
    },
    AuthzRow {
        service_fn: "get_client_roles",
        policy_fn: "can_view_client",
        action: actions::CLIENT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 514,
    },
    AuthzRow {
        service_fn: "get_clients",
        policy_fn: "can_view_client",
        action: actions::CLIENT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 538,
    },
    AuthzRow {
        service_fn: "get_redirect_uris",
        policy_fn: "can_view_client",
        action: actions::CLIENT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 561,
    },
    AuthzRow {
        service_fn: "get_post_logout_redirect_uris",
        policy_fn: "can_view_client",
        action: actions::CLIENT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 584,
    },
    AuthzRow {
        service_fn: "update_client",
        policy_fn: "can_update_client",
        action: actions::CLIENT_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 608,
    },
    AuthzRow {
        service_fn: "update_redirect_uri",
        policy_fn: "can_update_client",
        action: actions::CLIENT_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 646,
    },
    AuthzRow {
        service_fn: "update_post_logout_redirect_uri",
        policy_fn: "can_update_client",
        action: actions::CLIENT_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/client/services.rs",
        line: 684,
    },
    AuthzRow {
        service_fn: "toggle_maintenance",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_TOGGLE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 111,
    },
    AuthzRow {
        service_fn: "add_client_whitelist_user",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 242,
    },
    AuthzRow {
        service_fn: "add_client_whitelist_role",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 263,
    },
    AuthzRow {
        service_fn: "remove_client_whitelist_entry",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 284,
    },
    AuthzRow {
        service_fn: "get_client_whitelist",
        policy_fn: "can_view_client",
        action: actions::MAINTENANCE_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 302,
    },
    AuthzRow {
        service_fn: "add_realm_whitelist_user",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 322,
    },
    AuthzRow {
        service_fn: "add_realm_whitelist_role",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 342,
    },
    AuthzRow {
        service_fn: "remove_realm_whitelist_entry",
        policy_fn: "can_update_client",
        action: actions::MAINTENANCE_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 362,
    },
    AuthzRow {
        service_fn: "get_realm_whitelist",
        policy_fn: "can_view_client",
        action: actions::MAINTENANCE_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewClients],
        self_bypass: false,
        file: "core/src/domain/maintenance/services.rs",
        line: 381,
    },
    AuthzRow {
        service_fn: "assign_role",
        policy_fn: "can_manage_members",
        action: actions::ORGANIZATION_MEMBER_ROLE_ASSIGN,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/organization/member_role_services.rs",
        line: 141,
    },
    AuthzRow {
        service_fn: "revoke_role",
        policy_fn: "can_manage_members",
        action: actions::ORGANIZATION_MEMBER_ROLE_REVOKE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/organization/member_role_services.rs",
        line: 161,
    },
    AuthzRow {
        service_fn: "list_roles",
        policy_fn: "can_view_organization",
        action: actions::ORGANIZATION_MEMBER_ROLE_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "core/src/domain/organization/member_role_services.rs",
        line: 181,
    },
    AuthzRow {
        service_fn: "create_realm",
        policy_fn: "can_create_realm",
        action: actions::REALM_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 327,
    },
    AuthzRow {
        service_fn: "delete_realm",
        policy_fn: "can_delete_realm",
        action: actions::REALM_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 575,
    },
    AuthzRow {
        service_fn: "get_realm_by_name",
        policy_fn: "can_view_realm",
        action: actions::REALM_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageRealm,
            Permissions::ViewRealm,
        ],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 621,
    },
    AuthzRow {
        service_fn: "get_realm_setting_by_name",
        policy_fn: "can_view_realm",
        action: actions::REALM_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageRealm,
            Permissions::ViewRealm,
        ],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 650,
    },
    AuthzRow {
        service_fn: "update_realm",
        policy_fn: "can_update_realm",
        action: actions::REALM_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 746,
    },
    AuthzRow {
        service_fn: "update_realm_setting",
        policy_fn: "can_update_realm",
        action: actions::REALM_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 789,
    },
    AuthzRow {
        service_fn: "get_smtp_config",
        policy_fn: "can_view_realm",
        action: actions::REALM_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageRealm,
            Permissions::ViewRealm,
        ],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 938,
    },
    AuthzRow {
        service_fn: "upsert_smtp_config",
        policy_fn: "can_update_realm",
        action: actions::REALM_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 968,
    },
    AuthzRow {
        service_fn: "delete_smtp_config",
        policy_fn: "can_update_realm",
        action: actions::REALM_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageRealm],
        self_bypass: false,
        file: "core/src/domain/realm/services.rs",
        line: 1012,
    },
    AuthzRow {
        service_fn: "create_role",
        policy_fn: "can_create_role",
        action: actions::ROLE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 96,
    },
    AuthzRow {
        service_fn: "delete_role",
        policy_fn: "can_delete_role",
        action: actions::ROLE_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 150,
    },
    AuthzRow {
        service_fn: "get_role",
        policy_fn: "can_view_role",
        action: actions::ROLE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewRoles,
        ],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 190,
    },
    AuthzRow {
        service_fn: "get_roles",
        policy_fn: "can_view_role",
        action: actions::ROLE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewRoles,
        ],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 215,
    },
    AuthzRow {
        service_fn: "get_user_roles",
        policy_fn: "can_view_role",
        action: actions::ROLE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewRoles,
        ],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 238,
    },
    AuthzRow {
        service_fn: "update_role",
        policy_fn: "can_update_role",
        action: actions::ROLE_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 262,
    },
    AuthzRow {
        service_fn: "update_role_permissions",
        policy_fn: "can_update_role",
        action: actions::ROLE_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/role/services.rs",
        line: 310,
    },
    AuthzRow {
        service_fn: "delete_user",
        policy_fn: "can_update_user",
        action: actions::USER_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 164,
    },
    AuthzRow {
        service_fn: "reset_password",
        policy_fn: "can_update_user",
        action: actions::USER_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 220,
    },
    AuthzRow {
        service_fn: "update_user",
        policy_fn: "can_update_user",
        action: actions::USER_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 346,
    },
    AuthzRow {
        service_fn: "get_users",
        policy_fn: "can_view_user",
        action: actions::USER_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 409,
    },
    AuthzRow {
        service_fn: "assign_role",
        policy_fn: "can_update_user",
        action: actions::USER_ROLE_ASSIGN,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 433,
    },
    AuthzRow {
        service_fn: "bulk_delete_users",
        policy_fn: "can_delete_user",
        action: actions::USER_BULK_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 487,
    },
    AuthzRow {
        service_fn: "create_user",
        policy_fn: "can_create_user",
        action: actions::USER_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 536,
    },
    AuthzRow {
        service_fn: "get_user",
        policy_fn: "can_view_user",
        action: actions::USER_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 590,
    },
    AuthzRow {
        service_fn: "unassign_role",
        policy_fn: "can_update_user",
        action: actions::USER_ROLE_UNASSIGN,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 613,
    },
    AuthzRow {
        service_fn: "get_user_permissions",
        policy_fn: "can_view_user_permissions",
        action: actions::USER_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: true,
        file: "core/src/domain/user/services.rs",
        line: 666,
    },
    AuthzRow {
        service_fn: "get_user_attributes",
        policy_fn: "can_view_user",
        action: actions::USER_ATTRIBUTE_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 705,
    },
    AuthzRow {
        service_fn: "set_user_attributes",
        policy_fn: "can_update_user",
        action: actions::USER_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 736,
    },
    AuthzRow {
        service_fn: "delete_user_attribute",
        policy_fn: "can_update_user",
        action: actions::USER_ATTRIBUTE_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 763,
    },
    AuthzRow {
        service_fn: "unlock_user",
        policy_fn: "can_update_user",
        action: actions::USER_UNLOCK,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "core/src/domain/user/services.rs",
        line: 791,
    },
    AuthzRow {
        service_fn: "create_client_scope",
        policy_fn: "can_create_scope",
        action: actions::CLIENT_SCOPE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/client_scope_service.rs",
        line: 93,
    },
    AuthzRow {
        service_fn: "get_client_scope",
        policy_fn: "can_view_scope",
        action: actions::CLIENT_SCOPE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageClientScopes,
            Permissions::ViewClientScopes,
        ],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/client_scope_service.rs",
        line: 133,
    },
    AuthzRow {
        service_fn: "get_client_scopes",
        policy_fn: "can_view_scope",
        action: actions::CLIENT_SCOPE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageClientScopes,
            Permissions::ViewClientScopes,
        ],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/client_scope_service.rs",
        line: 173,
    },
    AuthzRow {
        service_fn: "update_client_scope",
        policy_fn: "can_update_scope",
        action: actions::CLIENT_SCOPE_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/client_scope_service.rs",
        line: 215,
    },
    AuthzRow {
        service_fn: "delete_client_scope",
        policy_fn: "can_delete_scope",
        action: actions::CLIENT_SCOPE_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/client_scope_service.rs",
        line: 249,
    },
    AuthzRow {
        service_fn: "create_protocol_mapper",
        policy_fn: "can_update_scope",
        action: actions::PROTOCOL_MAPPER_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/protocol_mapper_service.rs",
        line: 83,
    },
    AuthzRow {
        service_fn: "update_protocol_mapper",
        policy_fn: "can_update_scope",
        action: actions::PROTOCOL_MAPPER_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/protocol_mapper_service.rs",
        line: 118,
    },
    AuthzRow {
        service_fn: "delete_protocol_mapper",
        policy_fn: "can_update_scope",
        action: actions::PROTOCOL_MAPPER_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/protocol_mapper_service.rs",
        line: 148,
    },
    AuthzRow {
        service_fn: "assign_scope_to_client",
        policy_fn: "can_update_scope",
        action: actions::SCOPE_MAPPING_ASSIGN,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/scope_mapping_service.rs",
        line: 92,
    },
    AuthzRow {
        service_fn: "unassign_scope_from_client",
        policy_fn: "can_update_scope",
        action: actions::SCOPE_MAPPING_UNASSIGN,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageClientScopes],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/scope_mapping_service.rs",
        line: 137,
    },
    AuthzRow {
        service_fn: "get_client_scopes",
        policy_fn: "can_view_scope",
        action: actions::SCOPE_MAPPING_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageClientScopes,
            Permissions::ViewClientScopes,
        ],
        self_bypass: false,
        file: "libs/ferriskey-aegis/src/services/scope_mapping_service.rs",
        line: 170,
    },
    AuthzRow {
        service_fn: "fetch_flows",
        policy_fn: "can_view_flows",
        action: actions::FLOW_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-compass/src/services.rs",
        line: 80,
    },
    AuthzRow {
        service_fn: "get_flow",
        policy_fn: "can_view_flows",
        action: actions::FLOW_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-compass/src/services.rs",
        line: 106,
    },
    AuthzRow {
        service_fn: "get_stats",
        policy_fn: "can_view_flows",
        action: actions::FLOW_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-compass/src/services.rs",
        line: 140,
    },
    AuthzRow {
        service_fn: "get_daily_activity_stats",
        policy_fn: "can_view_flows",
        action: actions::FLOW_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-compass/src/services.rs",
        line: 164,
    },
    AuthzRow {
        service_fn: "get_credentials",
        policy_fn: "can_view_user",
        action: actions::CREDENTIAL_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ViewUsers],
        self_bypass: false,
        file: "libs/ferriskey-domain/src/credential/services.rs",
        line: 61,
    },
    AuthzRow {
        service_fn: "delete_credential",
        policy_fn: "can_delete_user",
        action: actions::CREDENTIAL_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-domain/src/credential/services.rs",
        line: 90,
    },
    AuthzRow {
        service_fn: "get_templates_by_realm",
        policy_fn: "can_view_email_template",
        action: actions::EMAIL_TEMPLATE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageEmailTemplates,
            Permissions::ViewEmailTemplates,
        ],
        self_bypass: false,
        file: "libs/ferriskey-mail/src/email_template/services.rs",
        line: 79,
    },
    AuthzRow {
        service_fn: "get_template",
        policy_fn: "can_view_email_template",
        action: actions::EMAIL_TEMPLATE_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageEmailTemplates,
            Permissions::ViewEmailTemplates,
        ],
        self_bypass: false,
        file: "libs/ferriskey-mail/src/email_template/services.rs",
        line: 100,
    },
    AuthzRow {
        service_fn: "create_template",
        policy_fn: "can_manage_email_template",
        action: actions::EMAIL_TEMPLATE_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageEmailTemplates],
        self_bypass: false,
        file: "libs/ferriskey-mail/src/email_template/services.rs",
        line: 122,
    },
    AuthzRow {
        service_fn: "update_template",
        policy_fn: "can_manage_email_template",
        action: actions::EMAIL_TEMPLATE_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageEmailTemplates],
        self_bypass: false,
        file: "libs/ferriskey-mail/src/email_template/services.rs",
        line: 158,
    },
    AuthzRow {
        service_fn: "delete_template",
        policy_fn: "can_manage_email_template",
        action: actions::EMAIL_TEMPLATE_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageEmailTemplates],
        self_bypass: false,
        file: "libs/ferriskey-mail/src/email_template/services.rs",
        line: 194,
    },
    AuthzRow {
        service_fn: "create_group",
        policy_fn: "can_manage_members",
        action: actions::GROUP_CREATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 216,
    },
    AuthzRow {
        service_fn: "get_group",
        policy_fn: "can_view_organization",
        action: actions::GROUP_READ,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 252,
    },
    AuthzRow {
        service_fn: "list_groups",
        policy_fn: "can_view_organization",
        action: actions::GROUP_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 268,
    },
    AuthzRow {
        service_fn: "update_group",
        policy_fn: "can_manage_members",
        action: actions::GROUP_UPDATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 289,
    },
    AuthzRow {
        service_fn: "delete_group",
        policy_fn: "can_manage_members",
        action: actions::GROUP_DELETE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 321,
    },
    AuthzRow {
        service_fn: "add_member",
        policy_fn: "can_manage_members",
        action: actions::GROUP_MEMBER_CREATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 338,
    },
    AuthzRow {
        service_fn: "remove_member",
        policy_fn: "can_manage_members",
        action: actions::GROUP_MEMBER_DELETE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 370,
    },
    AuthzRow {
        service_fn: "list_members",
        policy_fn: "can_view_organization",
        action: actions::GROUP_MEMBER_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 389,
    },
    AuthzRow {
        service_fn: "assign_role",
        policy_fn: "can_manage_members",
        action: actions::GROUP_ROLE_ASSIGN,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 425,
    },
    AuthzRow {
        service_fn: "revoke_role",
        policy_fn: "can_manage_members",
        action: actions::GROUP_ROLE_REVOKE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 446,
    },
    AuthzRow {
        service_fn: "list_roles",
        policy_fn: "can_view_organization",
        action: actions::GROUP_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 465,
    },
    AuthzRow {
        service_fn: "list_attributes",
        policy_fn: "can_view_organization",
        action: actions::GROUP_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 487,
    },
    AuthzRow {
        service_fn: "upsert_attribute",
        policy_fn: "can_manage_members",
        action: actions::GROUP_ATTRIBUTE_UPDATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 506,
    },
    AuthzRow {
        service_fn: "delete_attribute",
        policy_fn: "can_manage_members",
        action: actions::GROUP_ATTRIBUTE_DELETE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/group_services.rs",
        line: 530,
    },
    AuthzRow {
        service_fn: "create_organization",
        policy_fn: "can_create_organization",
        action: actions::ORGANIZATION_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 117,
    },
    AuthzRow {
        service_fn: "get_organization",
        policy_fn: "can_view_organization",
        action: actions::ORGANIZATION_READ,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 167,
    },
    AuthzRow {
        service_fn: "list_organizations",
        policy_fn: "can_create_organization",
        action: actions::ORGANIZATION_LIST,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 182,
    },
    AuthzRow {
        service_fn: "update_organization",
        policy_fn: "can_update_organization",
        action: actions::ORGANIZATION_UPDATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 204,
    },
    AuthzRow {
        service_fn: "delete_organization",
        policy_fn: "can_delete_organization",
        action: actions::ORGANIZATION_DELETE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 243,
    },
    AuthzRow {
        service_fn: "list_attributes",
        policy_fn: "can_view_organization",
        action: actions::ORGANIZATION_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 263,
    },
    AuthzRow {
        service_fn: "upsert_attribute",
        policy_fn: "can_update_organization",
        action: actions::ORGANIZATION_ATTRIBUTE_UPDATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 283,
    },
    AuthzRow {
        service_fn: "delete_attribute",
        policy_fn: "can_update_organization",
        action: actions::ORGANIZATION_ATTRIBUTE_DELETE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 313,
    },
    AuthzRow {
        service_fn: "add_member",
        policy_fn: "can_manage_members",
        action: actions::ORGANIZATION_MEMBER_CREATE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 333,
    },
    AuthzRow {
        service_fn: "remove_member",
        policy_fn: "can_manage_members",
        action: actions::ORGANIZATION_MEMBER_DELETE,
        resource: EntityType::ORGANIZATION,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 377,
    },
    AuthzRow {
        service_fn: "list_members",
        policy_fn: "can_view_organization",
        action: actions::ORGANIZATION_MEMBER_LIST,
        resource: EntityType::ORGANIZATION,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageUsers,
            Permissions::ViewUsers,
        ],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 403,
    },
    AuthzRow {
        service_fn: "list_user_organizations",
        policy_fn: "can_create_organization",
        action: actions::ORGANIZATION_LIST,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageUsers],
        self_bypass: false,
        file: "libs/ferriskey-organization/src/services.rs",
        line: 420,
    },
    AuthzRow {
        service_fn: "get_policy",
        policy_fn: "can_view_password_policy",
        action: actions::PASSWORD_POLICY_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-password-policy/src/service.rs",
        line: 47,
    },
    AuthzRow {
        service_fn: "update_policy",
        policy_fn: "can_update_password_policy",
        action: actions::PASSWORD_POLICY_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-password-policy/src/service.rs",
        line: 65,
    },
    AuthzRow {
        service_fn: "list_layouts",
        policy_fn: "can_manage_layouts",
        action: actions::PORTAL_LAYOUT_LIST,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-layouts/src/services.rs",
        line: 70,
    },
    AuthzRow {
        service_fn: "get_layout",
        policy_fn: "can_manage_layouts",
        action: actions::PORTAL_LAYOUT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-layouts/src/services.rs",
        line: 89,
    },
    AuthzRow {
        service_fn: "create_layout",
        policy_fn: "can_manage_layouts",
        action: actions::PORTAL_LAYOUT_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-layouts/src/services.rs",
        line: 111,
    },
    AuthzRow {
        service_fn: "update_layout",
        policy_fn: "can_manage_layouts",
        action: actions::PORTAL_LAYOUT_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-layouts/src/services.rs",
        line: 136,
    },
    AuthzRow {
        service_fn: "set_default_layout",
        policy_fn: "can_manage_layouts",
        action: actions::PORTAL_LAYOUT_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-layouts/src/services.rs",
        line: 157,
    },
    AuthzRow {
        service_fn: "delete_layout",
        policy_fn: "can_manage_layouts",
        action: actions::PORTAL_LAYOUT_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-layouts/src/services.rs",
        line: 178,
    },
    AuthzRow {
        service_fn: "get_theme",
        policy_fn: "can_view_theme",
        action: actions::PORTAL_THEME_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 72,
    },
    AuthzRow {
        service_fn: "update_theme",
        policy_fn: "can_manage_theme",
        action: actions::PORTAL_THEME_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 96,
    },
    AuthzRow {
        service_fn: "list_themes",
        policy_fn: "can_view_theme",
        action: actions::PORTAL_THEME_LIST,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 132,
    },
    AuthzRow {
        service_fn: "get_theme_by_id",
        policy_fn: "can_view_theme",
        action: actions::PORTAL_THEME_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 153,
    },
    AuthzRow {
        service_fn: "create_theme",
        policy_fn: "can_manage_theme",
        action: actions::PORTAL_THEME_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 175,
    },
    AuthzRow {
        service_fn: "update_theme_metadata",
        policy_fn: "can_manage_theme",
        action: actions::PORTAL_THEME_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 196,
    },
    AuthzRow {
        service_fn: "update_theme_page",
        policy_fn: "can_manage_theme",
        action: actions::PORTAL_THEME_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 223,
    },
    AuthzRow {
        service_fn: "activate_theme",
        policy_fn: "can_manage_theme",
        action: actions::PORTAL_THEME_ACTIVATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 264,
    },
    AuthzRow {
        service_fn: "delete_theme",
        policy_fn: "can_manage_theme",
        action: actions::PORTAL_THEME_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-portal-theme/src/services.rs",
        line: 300,
    },
    AuthzRow {
        service_fn: "fetch_events",
        policy_fn: "can_view_events",
        action: actions::SECURITY_EVENT_READ,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-seawatch/src/services.rs",
        line: 72,
    },
    AuthzRow {
        service_fn: "verify_realm_chain",
        policy_fn: "can_view_events",
        action: actions::SECURITY_EVENT_VERIFY_CHAIN,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm],
        self_bypass: false,
        file: "libs/ferriskey-seawatch/src/services.rs",
        line: 102,
    },
    AuthzRow {
        service_fn: "get_webhooks_by_realm",
        policy_fn: "can_view_webhook",
        action: actions::WEBHOOK_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageWebhooks,
            Permissions::ViewWebhooks,
        ],
        self_bypass: false,
        file: "libs/ferriskey-webhook/src/services.rs",
        line: 76,
    },
    AuthzRow {
        service_fn: "get_webhooks_by_subscribers",
        policy_fn: "can_view_webhook",
        action: actions::WEBHOOK_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageWebhooks,
            Permissions::ViewWebhooks,
        ],
        self_bypass: false,
        file: "libs/ferriskey-webhook/src/services.rs",
        line: 102,
    },
    AuthzRow {
        service_fn: "get_webhook",
        policy_fn: "can_view_webhook",
        action: actions::WEBHOOK_READ,
        resource: EntityType::REALM,
        permissions: &[
            Permissions::ManageRealm,
            Permissions::ManageWebhooks,
            Permissions::ViewWebhooks,
        ],
        self_bypass: false,
        file: "libs/ferriskey-webhook/src/services.rs",
        line: 128,
    },
    AuthzRow {
        service_fn: "create_webhook",
        policy_fn: "can_create_webhook",
        action: actions::WEBHOOK_CREATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageWebhooks],
        self_bypass: false,
        file: "libs/ferriskey-webhook/src/services.rs",
        line: 155,
    },
    AuthzRow {
        service_fn: "update_webhook",
        policy_fn: "can_update_webhook",
        action: actions::WEBHOOK_UPDATE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageWebhooks],
        self_bypass: false,
        file: "libs/ferriskey-webhook/src/services.rs",
        line: 200,
    },
    AuthzRow {
        service_fn: "delete_webhook",
        policy_fn: "can_delete_webhook",
        action: actions::WEBHOOK_DELETE,
        resource: EntityType::REALM,
        permissions: &[Permissions::ManageRealm, Permissions::ManageWebhooks],
        self_bypass: false,
        file: "libs/ferriskey-webhook/src/services.rs",
        line: 245,
    },
];
