/*
 * FerrisKey API
 *
 * FerrisKey API
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: pro.nathaelbonnal@gmail.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JwtToken {
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "expires_in")]
    pub expires_in: i32,
    #[serde(
        rename = "id_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id_token: Option<Option<String>>,
    #[serde(
        rename = "refresh_expires_in",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_expires_in: Option<Option<i32>>,
    #[serde(
        rename = "refresh_token",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub refresh_token: Option<Option<String>>,
    #[serde(
        rename = "session_state",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub session_state: Option<Option<String>>,
    #[serde(rename = "token_type")]
    pub token_type: String,
}

impl JwtToken {
    pub fn new(access_token: String, expires_in: i32, token_type: String) -> JwtToken {
        JwtToken {
            access_token,
            expires_in,
            id_token: None,
            refresh_expires_in: None,
            refresh_token: None,
            session_state: None,
            token_type,
        }
    }
}
