name: docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      push:
        type: boolean
        default: false
        description: "Whether to push the image"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        target:
          - api
          - operator
          - webapp
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: set up builx
        uses: docker/setup-buildx-action@v3
      
      - name: get image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/ferriskey/ferriskey-${{ matrix.target }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=ref,event=pr
            type=sha

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          target: ${{ matrix.target }}
          push: ${{ inputs.push == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
