name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: set up rust toolchain
        id: rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy,rustfmt

      - name: set up python
        uses: actions/setup-python@v5

      - name: set up node
        uses: actions/setup-node@v4

      - name: install pnpm
        run: npm install -g pnpm@latest-10

      - name: cache rust build
        uses: actions/cache@v4
        with:
          path: target
          key: clippy-${{ runner.arch }}-${{ steps.rust.outputs.cachekey }}-${{ hashFiles('Cargo.*', '**/*.rs') }}
          restore-keys: |
            clippy-${{ runner.arch }}-${{ steps.rust.outputs.cachekey }}-

      - name: cache rust build
        uses: actions/cache@v4
        with:
          path: front/node_modules
          key: node-${{ runner.arch }}-${{ hashFiles('front/pnpm-lock.yaml') }}
          restore-keys: |
            clippy-${{ runner.arch }}-${{ steps.rust.outputs.cachekey }}-

      - name: install node modules
        working-directory: front
        run: pnpm install

      - name: run pre-commit
        uses: pre-commit/action@v3.0.1
