name: release

permissions:
  contents: write

on:
  push:
    tags:
      - v*.*.*
      - v*.*.*-rc*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: check prerelease
        id: prerelease
        run: |
          if [[ "$GITHUB_REF" == *"-rc"* ]]; then
            echo "prerelease=true" >> "$GITHUB_OUTPUT"
          else
            echo "prerelease=false" >> "$GITHUB_OUTPUT"
          fi

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: ${{ steps.prerelease.outputs.prerelease }}
