name: Draft Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  frontend:
    name: "Draft release frontend"
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
