name: Release Development

on:
  push:
    branches:
      - main


permissions:
  packages: write


jobs:
  prepare-ci:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract_version.outputs.result }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Extract version from short-sha
        id: extract_version
        run: |
          SHORT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "RELEASE_TAG=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          echo "RELEASE_VERSION=${SHORT_SHA}" >> "$GITHUB_OUTPUT"
          echo "::set-output name=result::${SHORT_SHA}"
  build-doc:
    needs: [prepare-ci]
    uses: ferriskey/ferriskey/.github/workflows/build-and-push-docker.yaml@main
    with:
      registry: ghcr.io
      registry_username: ferriskey
      image_name: ferriskey-docs
      repository: ferriskey/ferriskey
      tag: ${{ needs.prepare-ci.outputs.version }}
      ref: main
      context: 'docs'
      dockerfile: ''
    secrets:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
  build-api:
    needs: [prepare-ci]
    uses: ferriskey/ferriskey/.github/workflows/build-and-push-docker.yaml@main
    with:
      registry: ghcr.io
      registry_username: ferriskey
      image_name: ferriskey-api
      repository: ferriskey/ferriskey
      tag: ${{ needs.prepare-ci.outputs.version }}
      ref: main
      context: 'api'
      dockerfile: ''
    secrets:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
  build-operator:
    needs: [prepare-ci]
    uses: ferriskey/ferriskey/.github/workflows/build-and-push-docker.yaml@main
    with:
      registry: ghcr.io
      registry_username: ferriskey
      image_name: ferriskey-operator
      repository: ferriskey/ferriskey
      tag: ${{ needs.prepare-ci.outputs.version }}
      ref: main
      context: 'operator'
      dockerfile: ''
    secrets:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT: ${{ secrets.GITHUB_TOKEN }}
  build-front:
    needs: [prepare-ci]
    uses: ferriskey/ferriskey/.github/workflows/build-and-push-docker.yaml@main
    with:
      registry: ghcr.io
      registry_username: ferriskey
      image_name: ferriskey-front
      repository: ferriskey/ferriskey
      tag: ${{ needs.prepare-ci.outputs.version }}
      ref: main
      context: 'front'
      dockerfile: ''
    secrets:
      CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PAT: ${{ secrets.GITHUB_TOKEN }}

